before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    goarm:
      - 7
    main: ./cmd/m1-terraform-provider-helper
  
archives:
  - replacements:
      darwin: Darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc

brews:
  -
    tap:
      owner: kreuzwerker
      name: homebrew-taps

    download_strategy: CurlDownloadStrategy
    homepage: "https://github.com/kreuzwerker/m1-terraform-provider-helper"
    description: "CLI to support with downloading and compiling terraform providers for Mac with M1 chip."
