name: tests

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs:
  unit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: make test
      - name: Convert coverage
        uses: jandelgado/gcov2lcov-action@v1.0.5
        with:
          infile: ./dist/test_results/main/coverage.out
          outfile: ./dist/test_results/main/coverage.lcov
      - name: Upload coverage
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./dist/test_results/main/coverage.lcov